# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net
name: $(Date:yy.MM).$(Rev:r)

trigger: none

pool:
  vmImage: 'windows-latest'

variables:
- group: LMP

steps:

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DownloadSecureFile@1
  name: certificate
  inputs:
    secureFile: 'LMPModManager.pfx'





- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: codesigning@2
  inputs:
    secureFileId: 'LMPModManager.pfx'
    signCertPassword: '$(password)'
    files: '$(binariesLocation)/*.exe'
    timeServer: 'http://timestamp.digicert.com'
    hashingAlgorithm: 'SHA256'
    description: 'A Modmanager for pokemon games'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      **\**
      !ModManagerSource\**
      !.git\**
      !.gitignore
      !azure-pipelines.yml
    TargetFolder: '$(binariesLocation)'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(binariesLocation)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(windowsBinariesArchiveName)'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'lmp modloader'
    repositoryName: 'alchemis/LMP-Mod-Pack'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: 'modloader-$(Build.BuildNumber)'
    title: '$(releaseVersionName)'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
