# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net
name: $(Date:yy.MM).$(Rev:r)

trigger:
  tags:
    include:
      - 'modloader.*'

  

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  binariesLocation: '$(Build.SourcesDirectory)/ModLoaderSource/ModLoader/bin/Release/'
  releaseVersionName: 'release-v$(Build.BuildNumber)-$(Build.SourceBranchName)'
  windowsBinariesArchiveName: '$(releaseVersionName)-winx86x64.zip'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(binariesLocation)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(windowsBinariesArchiveName)'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'ModLoader PAT'
    repositoryName: 'Tilation/LMP-Mod-Pack-with-modloader'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: 'modloader-$(Build.BuildNumber)'
    title: '$(releaseVersionName)'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
